### ISSUE TITLE
we can't create a account in c9 , we are chinese!

### ISSUE THREAD

**Issue by pedrogao** [FreeCodeCampChina/freecodecamp.cn#396] opened 2017-09-24 13:14 UTC
Challenge [Save your Code Revisions Forever with Git](https://www.freecodecamp.cn/challenges/save-your-code-revisions-forever-with-git) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by wudifeixue** [comment] 2017-09-30 16:34
duplicate of #394

**Closed as completed by wudifeixue** 2017-09-30 16:34 UTC
Labels: duplicate
